name: uslce
recipe: drupal6
config:
  php: '8.2'
  composer_version: '2-latest'
  via: apache:2.4
  webroot: .
  drush: ^8.4.12
  xdebug: true
services:
  database:
    type: mysql:5.7
    run_as_root:
      # Creates the extra databases as root since the app user does not have those privileges
      - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS cg_game; GRANT ALL PRIVILEGES ON cg_game.* TO 'drupal6'@'%' IDENTIFIED by 'drupal6';"
      - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS uslce_game; GRANT ALL PRIVILEGES ON uslce_game.* TO 'drupal6'@'%' IDENTIFIED by 'drupal6';"
      - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS stl1904_game; GRANT ALL PRIVILEGES ON stl1904_game.* TO 'drupal6'@'%' IDENTIFIED by 'drupal6';"
      - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS stl2124_game; GRANT ALL PRIVILEGES ON stl2124_game.* TO 'drupal6'@'%' IDENTIFIED by 'drupal6';"
      - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS detroit_game; GRANT ALL PRIVILEGES ON detroit_game.* TO 'drupal6'@'%' IDENTIFIED by 'drupal6';"
      - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS elysian_game; GRANT ALL PRIVILEGES ON elysian_game.* TO 'drupal6'@'%' IDENTIFIED by 'drupal6';"
      - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS wonderland_game; GRANT ALL PRIVILEGES ON wonderland_game.* TO 'drupal6'@'%' IDENTIFIED by 'drupal6';"
  pma:
    type: phpmyadmin
    hosts:
      - database
    overrides:
      image: phpmyadmin:latest
proxy:
  pma:
    - pma.lndo.site

