# docker-compose.yml

# start the container with:
# $ docker compose up -d

# ssh in with:
# $ docker exec -t -i usl15-game-web-1 /bin/bash

services:
  web:
    image: ziquid/zg:latest
    volumes:
      - .:/var/www/html
    expose:
      - "80"
    labels:
      - "traefik.http.routers.zg.rule=(Host(`10.0.2.2`) || Host(`zg.docker.localhost`) || Host(`zg.asrock.lan`) || Host(`zg.dev.games.ziquid.com`) || Host(`zg.games.ziquid.com`))"
    networks:
      - traefik
  db:
    image: bitnami/mysql:5.7
    volumes:
      - ./db/backups:/var/mysql/backups
      - ./db/data:/bitnami/mysql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    networks:
      - traefik
  pma:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    expose:
      - "80"
    labels:
      - "traefik.http.routers.zg-pma.rule=(Host(`zg.docker.localhost`) || Host(`zg.asrock.lan`) || Host(`zg.dev.games.ziquid.com`) || Host(`zg.games.ziquid.com`)) && PathPrefix(`/pma`)"
      - "traefik.http.middlewares.zgpma-stripprefix.stripprefix.prefixes=/pma"
      - "traefik.http.routers.zg-pma.middlewares=zgpma-stripprefix@docker"
    networks:
      - traefik

networks:
  traefik:
    driver: bridge
    name: traefik
    external: true
