# docker-compose.yml

# start the container with:
# $ docker compose up -d

# ssh in with:
# $ docker exec -t -i usl15-game-web-1 /bin/bash

services:
  web:
    image: ghcr.io/ziquid/zg:latest
    volumes:
      - .:/var/www/html
    expose:
      - "80"
    labels:
      - "traefik.http.routers.zg.rule=(Host(`10.0.2.2`) || Host(`zg.docker.localhost`) || Host(`zg.asrock.lan`) || Host(`zg.dev.games.ziquid.com`) || Host(`zg.games.ziquid.com`))"
      - "traefik.enable=true"
      - "traefik.http.routers.zg.entrypoints=web,websecure"
      - "traefik.http.services.zg.loadbalancer.server.port=80"
    networks:
      - traefik
      - zgdb
  db:
    image: bitnami/mysql:8.4 # 5.7
    volumes:
      - ./db/backups:/var/mysql/backups
      - ./db/data:/bitnami/mysql/data
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/start:/docker-entrypoint-startdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    networks:
      - zgdb
#     labels:
#       - "traefik.enable=true"
  pma:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    expose:
      - "80"
    labels:
      - "traefik.http.routers.zg-pma.rule=(Host(`zg.docker.localhost`) || Host(`zg.asrock.lan`) || Host(`zg.dev.games.ziquid.com`) || Host(`zg.games.ziquid.com`)) && PathPrefix(`/pma`)"
      - "traefik.http.middlewares.zgpma-stripprefix.stripprefix.prefixes=/pma"
      - "traefik.http.routers.zg-pma.middlewares=zgpma-stripprefix@docker"
      - "traefik.enable=true"
      - "traefik.http.routers.zg-pma.entrypoints=web,websecure"
      - "traefik.http.services.zg-pma.loadbalancer.server.port=80"
    networks:
      - traefik
      - zgdb

networks:
  zgdb:
    name: zgdb
    driver: bridge
  traefik:
#    driver: bridge
    name: traefik
    external: true
