<?php

function celestial_glory_help($path, $arg) {

  $output = '';

  switch ($path) {
    case "admin/help#celestial_glory":
      $output = '<p>'.  t('Back end for <em>Celestial Glory</em> game') .'</p>';
      break;
  }

  return $output;
}

function celestial_glory_perm() {
  return ['access celestial_glory content'];
}

require_once(drupal_get_path('module', 'celestial_glory') . '/menu.inc');
require_once(drupal_get_path('module', 'celestial_glory') . '/admin.inc');
//require_once(drupal_get_path('module', 'celestial_glory') . '/functions.inc');

function celestial_glory_cron() {

  db_set_active('game_cg');

// save old approval ratings

  $sql = 'update elected_officials set approval_45 = approval_30,
    approval_30 = approval_15, approval_15 = approval_rating;';
  $result = db_query($sql);

// move all elected officials toward a 60% approval rating

  $sql = 'update elected_officials set approval_rating = 60
    where (approval_rating >= 59.75 AND approval_rating <= 60.25);';
  $result = db_query($sql);

  $sql = 'update elected_officials
    set approval_rating = approval_rating + 0.25
    where approval_rating <= 59.75;';
  $result = db_query($sql);

  $sql = 'update elected_officials
    set approval_rating = approval_rating - 0.25
    where approval_rating >= 60.25;';
  $result = db_query($sql);

  $sql = 'update elected_officials
    set approval_rating = 0 where approval_rating < 0;';
  $result = db_query($sql);

  $sql = 'update elected_officials
    set approval_rating = 100 where approval_rating > 100;';
  $result = db_query($sql);

// move all hoods toward a 50 beauty rating

// all hoods: move by 0.25

  $sql = 'update neighborhoods set rating = 50
    where (rating >= 49.75 AND rating <= 50.25);';
  $result = db_query($sql);

  $sql = 'update neighborhoods
    set rating = rating + 0.25
    where rating < 49.75;';
  $result = db_query($sql);

  $sql = 'update neighborhoods
    set rating = rating - 0.25
    where rating > 50.25;';
  $result = db_query($sql);

// hoods with no CP: move by an additional 1.75 (total: 2.0)

  $sql = 'update neighborhoods
    set rating = rating + 1.75
    where rating < 48.25 and id not in
    (SELECT users.fkey_neighborhoods_id FROM elected_officials
    left join users on elected_officials.fkey_users_id = users.id
    where fkey_elected_positions_id = 1);';
  $result = db_query($sql);

  $sql = 'update neighborhoods
    set rating = rating - 1.75
    where rating > 51.75 and id not in
    (SELECT users.fkey_neighborhoods_id FROM elected_officials
    left join users on elected_officials.fkey_users_id = users.id
    where fkey_elected_positions_id = 1);';
  $result = db_query($sql);

// give hoods residents to match - each gets $addition plus rating / 6

  $addition = 0; // winter
//  $addition = 5; // spring / fall
//  $addition = 10; // summer
  $addition = -4; // testing jwc 26Jul2014

  $sql = 'UPDATE `neighborhoods` SET residents = residents + 1
    WHERE floor(rating / 6) > (residents - %d);'; // AND rand() > 0.9';
  $result = db_query($sql, $addition);

  $sql = 'UPDATE `neighborhoods` SET residents = residents - 1
    WHERE floor(rating / 6) < (residents - %d) and residents > 0;'; // AND rand() > 0.9';
  $result = db_query($sql, $addition);


// april fools' 2013 -- move 50 people at random
/*
  $sql = 'select users.id from users
    left join elected_officials on users.id = elected_officials.fkey_users_id
    where elected_officials.id IS NULL
    and users.level >= 25
    order by rand()
    limit 50;';
  $result = db_query($sql);
  $data = array();
  while ($item = db_fetch_object($result)) $data[] = $item;

  foreach ($data as $item) {

    $sql = 'select id from neighborhoods where xcoor > 0 and ycoor > 0
      order by rand() limit 1;';
    $result = db_query($sql);
    $hood = db_fetch_object($result);

    $sql = 'update users set fkey_neighborhoods_id = %d
      where id = %d;';
    $result = db_query($sql, $hood->id, $item->id);

  }
*/

  // update maps now done after each CP toss.
   _celestial_glory_draw_maps();

// prune old log files
  $sql = 'delete from challenge_messages where timestamp < "%s"
    limit 10000;';
  $result = db_query($sql, date('Y-m-d H:i:s', time() - 400000));
// a little over a month

  $sql = 'delete from challenge_history where timestamp < "%s"
    limit 5000;';
  $result = db_query($sql, date('Y-m-d H:i:s', time() - 400000));

// add roses
  $sql = 'update neighborhoods
    set roses = least(99, roses + (FLOOR(RAND() * 3)))
    where roses < 99;';
  $result = db_query($sql);

  $sql = 'update neighborhoods
    set roses = greatest(0, roses - (1 + FLOOR(RAND() * 5)))
    where roses > 5 and id <> 6;';
  $result = db_query($sql);

  // Move debatebots.
  $sql = 'select users.id from users
    where meta = "debatebot";';
  $result = db_query($sql);
  $data = array();
  while ($item = db_fetch_object($result)) $data[] = $item;

  foreach ($data as $item) {

    $sql = 'select id from neighborhoods where has_elections = 1
      order by rand() limit 1;';
    $result = db_query($sql);
    $hood = db_fetch_object($result);

    $sql = 'update users set fkey_neighborhoods_id = %d, money = money + 100
      where id = %d;';
    $result = db_query($sql, $hood->id, $item->id);

  }

  // Add zombies?
  $sql = 'select count(*) as count from users where last_access < "%s"
    and meta = "";';
  $result = db_query($sql, date('Y-m-d', time() - (86400 * 180)));
  $old_users = db_fetch_object($result);

  // 100 or more old accounts?  Check zombie count.
  if ($old_users->count >= 100) {
    $sql = 'select count(*) as count from users where meta = "zombie";';
    $result = db_query($sql);
    $zombies = db_fetch_object($result);

    // Fewer than 50 zombies?  Add 100 more.
    if ($zombies->count < 50) {

      $sql = 'select id from users where last_access < "%s"
        order by rand() limit 100;';
      $result = db_query($sql, date('Y-m-d', time() - (86400 * 180)));
      $zombie_users = array();
      while ($item = db_fetch_object($result)) $zombie_users[] = $item;

      // Change each user to a zombie.
      foreach ($zombie_users as $zombie) {
        $name = game_zombie_name();
        if ($zombie->level < 25) {
          $zombie->level += 25 + mt_rand(0,50);
        }
        $sql = 'update users set meta = "zombie", username = "%s", level = %d
          where id = %d;';
        $result = db_query($sql, $name, $zombie->level, $zombie->id);
      }

      // Notify the game players.
      $sql = 'insert into system_messages set message = "%s";';
      $result = db_query($sql,
        'Grrrr!&nbsp; Zombies have sprung up everywhere!');

    }

  }
  db_set_active('default');

}

function _celestial_glory_filter_profanity($message) {

  $profanity = array(
	'4r5e',
	'5h1t',
	'5hit',
	'a_s_s',
	'a55',
	'anal',
	'anus',
	'ar5e',
	'arrse',
	'arse',
	'a§§',
	'as.s',
	'ass',
	'asses',
	'assfucker',
	'ass-fucker',
	'assfukka',
	'asshole',
	'assholes',
	'asskisser',
	'asss',
	'asswad',
	'asswhole',
	'asswipe',
  'asz',
  'azz',
	'beotch',
	'b!tch',
	'b00bs',
	'b17ch',
	'b1tch',
	'badass',
	'badasss',
	'ballbag',
	'ballsack',
	'bastard',
	'beastial',
	'beastiality',
	'beastility',
	'beaver',
	'bellend',
	'belly whacker',
	'bestial',
	'bestiality',
	'beotch',
	'b!tch',
	'bytch',
	'bi+ch',
	'biatch',
	'bit.ch',
	'bitch',
	'bitcher',
	'bitchers',
	'bitches',
	'bitchin',
	'bitching',
	'bloody',
	'blow job',
	'blowjob',
	'blowjobs',
	'boiolas',
	'bollock',
	'bollok',
	'bonehead',
	'boner',
	'boob',
	'boobs',
	'booobs',
	'boooobs',
	'booooobs',
	'booooooobs',
	'browntown',
	'btch',
	'buceta',
	'bucket cunt',
//	'bugger',
	'bullshit',
	'bung hole',
	'butch',
	'butt breath',
	'butt hair',
	'buttface',
	'buttfuck',
	'buttfucker',
	'butthead',
	'buttheadddd',
	'butthole',
	'buttmuch',
	'buttpicker',
	'buttplug',
	'c0ck',
	'c0cksucker',
	'carpet muncher',
	'cawk',
	'chink',
	'cipa',
	'circle jerk',
	'cl1t',
	'clam',
	'clit',
	'clitoris',
	'clits',
	'cnut',
	'cobia',
	'cock',
	'cockface',
	'cockhead',
	'cockmunch',
	'cockmuncher',
	'cocks',
	'cocksuck',
	'cocksucked',
	'cocksucker',
	'cock-sucker',
	'cocksucking',
	'cocksucks',
	'cocksuka',
	'cok',
	'cokmuncher',
	'coksucka',
	'coon',
	'cooter',
	'cox',
	'crap',
	'cum',
	'cummer',
	'cumming',
	'cums',
	'cumshot',
	'cunilingus',
	'cunillingus',
	'cunnilingus',
	'cunnilingus',
	'cunt',
	'cuntlick',
	'cuntlicker',
	'cuntlicking',
	'cunts',
	'cyalis',
	'cyberfuc',
	'cyberfuck',
	'cyberfucked',
	'cyberfucker',
	'cyberfuckers',
	'cyberfucking',
	'dammit',
	'd1ck',
	'dam',
	'damn',
	'dbag',
	'dick',
	'dickk',
	'dickhead',
	'dike',
	'dildo',
	'dildos',
	'dink',
	'dinks',
	'dipshit',
	'dirsa',
	'dlck',
	'dog-fucker',
	'doggin',
	'dogging',
	'dong',
	'donkeyribber',
	'doosh',
	'douche bag',
	'duche',
	'dumbass',
	'dumbfuck',
	'dyke',
	'dyke',
	'ejaculate',
	'ejaculated',
	'ejaculates',
	'ejaculating',
	'ejaculatings',
	'ejaculation',
	'ejakulate',
	'fuc',
	'fuc k',
	'fu c k',
	'fukin',
	'fck',
	'fvk',
	'f u c k',
	'f u c k e r',
	'f_u_c_k',
	'f4nny',
	'fag',
	'fagget',
	'fagging',
	'faggit',
	'faggitt',
	'faggot',
	'faggs',
	'fagot',
	'fagot',
	'fagots',
	'fags',
	'fanny',
	'fannyflaps',
	'fannyfucker',
	'fanyy',
	'fart',
	'farted',
	'farting',
	'fartings',
	'farts',
	'farty',
	'fatass',
	'fatso',
	'fcuk',
	'fcuker',
	'fcuking',
	'feck',
	'fecker',
	'felatio',
	'felching',
	'fellate',
	'fellatio',
	'fellatio',
	'fingerfuck',
	'fingerfucked',
	'fingerfucker',
	'fingerfuckers',
	'fingerfucking',
	'fingerfucks',
	'fistfuck',
	'fistfucked',
	'fistfucker',
	'fistfuckers',
	'fistfucking',
	'fistfuckings',
	'fistfucks',
	'flange',
	'fook',
	'fooker',
	'fu.ck',
	'fuck',
	'fucka',
	'fucked',
	'fucker',
	'fuckers',
	'fuckers',
	'fuckhead',
	'fuckheads',
	'fuckin',
	'fucking',
	'fuckings',
	'fuckingshitmotherfucker',
	'fuckme',
	'fuckr',
	'fucks',
	'fuckwhit',
	'fuckwit',
	'fudge packer',
	'fudgepacker',
	'fuggin',
	'fuk',
	'fuker',
	'fukker',
	'fukkin',
	'fuks',
	'fukwhit',
	'fukwit',
	'furburger',
	'fux',
	'fux0r',
	'fvck',
	'gangbang',
	'gangbanged',
	'gangbangs',
	'gaylord',
	'gaysex',
	'gaysex',
	'gazongers',
	'goatse',
	'god-dam',
	'g--dam',
	'goddamn',
	'goddamn',
	'goddamned',
	'god-damned',
	'gonads',
	'gook',
	'guinne',
	'hard on',
	'hardcoresex',
	'hell',
	'heshe',
	'hoar',
	'hoare',
	'ho.es',
	'hoer',
	'homo',
	'hooker',
	'hore',
	'horniest',
	'horny',
	'hotsex',
	'hussy',
	'lmao',
	'lmfao',
	'jack off',
	'jackass',
	'jacking off',
	'jackoff',
	'jack-off',
	'jerk-off',
	'jism',
	'jiz',
	'jiz',
	'jizm',
	'jizz',
	'kawk',
	'kike',
	'knobead',
	'knobed',
	'knobend',
	'knobhead',
	'knobjocky',
	'knobjokey',
	'kock',
	'kondum',
	'kondums',
	'kum',
	'kummer',
	'kumming',
	'kums',
	'kunilingus',
	'kunilingus',
	'l3i+ch',
	'l3itch',
	'labia',
	'lesbian',
	'lesbo',
	'lmao',
	'lma0',
	'lmfa0',
	'm0f0',
	'm0fo',
	'm45terbate',
	'ma5terb8',
	'ma5terbate',
	'masterb8',
	'masterbat*',
	'masterbat3',
	'masterbate',
	'master-bate',
	'masterbation',
	'masterbations',
	'masturbate',
	'mof0',
	'mofo',
	'mo-fo',
	'mothafuck',
	'mothafucka',
	'mothafuckas',
	'mothafuckaz',
	'mothafucked',
	'mothafucker',
	'mothafuckers',
	'mothafuckin',
	'mothafucking',
	'mothafuckings',
	'mothafucks',
	'mother fucker',
	'motherfuck',
	'motherfuck',
	'motherfucked',
	'motherfucker',
	'motherfuckers',
	'motherfuckin',
	'motherfuckin',
	'motherfucking',
	'motherfuckings',
	'motherfuckka',
	'motherfucks',
	'muff',
	'mutha',
	'muthafecker',
	'muthafuckker',
	'muther',
	'mutherfucker',
	'n1gga',
	'n1gger',
	'nazi',
	'nigg3r',
	'nigg4h',
	'nigga',
	'niggah',
	'niggas',
	'niggaz',
	'nigger',
	'niggers',
	'nobhead',
	'nobjocky',
	'nobjokey',
	'numbnuts',
	'nutsack',
	'orgasim',
	'orgasims',
	'orgasm',
	'orgasms',
	'p0rn',
	'pawn',
	'pecker',
	'penis',
	'penisfucker',
	'phonesex',
	'phuck',
	'phuk',
	'phuked',
	'phuking',
	'phuking',
	'phukked',
	'phukking',
	'phuks',
	'phuks',
	'phuq',
	'phuq',
	'pigfucker',
	'pimp',
	'pimpis',
	'piss',
	'pissed',
	'pisser',
	'pissers',
	'pisses',
	'pissflaps',
	'pissin',
	'pissing',
	'pissoff',
	'pissrr',
	'poop',
	'porn',
	'porno',
	'pornography',
	'pornos',
	'pron',
	'pube',
	'pusse',
	'pussi',
	'pussies',
	'pussies',
	'pussy',
	'pussys',
	'pvssy',
	'queer',
	'rectum',
	'retard',
	'rimjaw',
	'rimming',
	'rape',
	'shlt',
	'sh!t',
	'sh!ts',
	'slut',
	's hit',
	's.o.b.',
	's_h_i_t',
	'sadist',
	'schlong',
	'screw',
	'screwing',
	'scroat',
	'scrote',
	'scrotum',
	'semen',
	'sex',
	'sh!+',
	'sh!t',
	'sh.it',
	'sh1t',
	'shag',
	'shagger',
	'shaggin',
	'shagging',
	'sheister',
	'shemale',
	'sh it',
	'shi+',
	'shit',
	'sh!t',
	'shitdick',
	'shite',
	'shited',
	'shited',
	'shitey',
	'shitfuck',
	'shitfull',
	'shitfull',
	'shithead',
	'shiting',
	'shitings',
	'shits',
	'shits',
	'shitted',
	'shitter',
	'shitters',
	'shitting',
	'shittings',
	'shitty',
	'shitty',
	'shiz',
	'sht',
	'shttim',
	'skank',
	'slag',
	'sleaze',
	'slut',
	'slut',
	'sluts',
	'smartass',
	'smegma',
	'smut',
	'snatch',
	'son-of-a-bitch',
	'spac',
	'spunk',
	'stupidass',
	't1tt1e5',
	't1tties',
	'teets',
	'teez',
	'testical',
	'testicle',
	'tit',
	'titfuck',
	'tits',
	'titt',
	'tittie5',
	'tittiefucker',
	'titties',
	'tittyfuck',
	'tittywank',
	'titwank',
	'tosser',
	'turd',
	'tw4t',
	'twat',
	'twathead',
	'twatty',
	'twunt',
	'twunter',
	'tampon',
	'v14gra',
	'v1gra',
	'vagina',
	'viagra',
	'vulva',
	'w00se',
	'wang',
	'wank',
	'wanker',
	'wanky',
	'weakass',
	'weakasss',
	'wetback',
	'whoar',
	'whore',
	'wtf',
	);

  $msg = str_replace(
    array('@', '$', "'", '.', '&#039;', '&quot;'),
    array('a', 's', ' ', ' ', ' ', ' '),
    $message);

  setlocale(LC_ALL, 'en_US');
  $msg = preg_replace('/[^A-Za-z0-9 ]/', '',
    iconv('utf-8', 'ascii//TRANSLIT', $msg));

  foreach ($profanity as $word) {
    $pattern = "/\b$word\b/i"; // Check word boundaries, ignoring case

    if (preg_match($pattern, $msg) == 1) return "XXX: found $word XXX";

  }

  return $message;

}

function _cg_fetch_user() {
  return zg_fetch_user();
}

function _celestial_glory_fetch_user() {
  return zg_fetch_user();
}

function _cg_header($game_user) {
  zg_fetch_header($game_user);
}

function _celestial_glory_header($game_user) {
  zg_fetch_header($game_user);
}
